version: '3.7'

services:

  product-service:
    image: rajendiranprabu/mm2-products-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8040:8040"
    networks:
      - product-network
    depends_on:
      - erueka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://erueka-server:8761/eureka

  erueka-server:
    image: rajendiranprabu/mm2-eurekadmo:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - product-network

networks:
  product-network: