spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apche.kafka.common.serialiaztion.StringDeserializer
     # value-deserializer: org.apche.kafka.common.serialiaztion.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer